language: node_js
sudo: false
node_js:
  - "10"
before_install:
  - npm install -g codecov
install:
  - npm install
jobs:
  include:
    - stage: Test with Mocha
      script:
        - NODE_ENV=test npm test
after_success: npm run coverage